name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y \
          git \
          gcc-9 \
          cmake \
          make \
          libev-dev \
          openssl \
          libssl-dev \
          systemd \
          libsystemd-dev \
          libyaml-dev \
          libatomic1 \
          zlib1g \
          zlib1g-dev \
          libzstd-dev \
          liblz4-dev \
          bzip2 \
          libbz2-dev \
          pkg-config \
          curl
      
    - name: Install PostgreSQL
      run: |
        sudo apt install -y curl ca-certificates
        sudo install -d /usr/share/postgresql-common/pgdg
        sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
        sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        sudo apt update
        sudo apt install -y postgresql-17 postgresql-server-dev-17 postgresql-contrib-17 postgresql-common
        
    - name: Set PostgreSQL Path and Verify Installation
      run: |
        echo "PATH=$PATH:/usr/lib/postgresql/17/bin" >> $GITHUB_ENV
        echo "PostgreSQL version:"
        /usr/lib/postgresql/17/bin/pg_config --version
        echo "Include directory:"
        /usr/lib/postgresql/17/bin/pg_config --includedir
        echo "Server include directory:"
        /usr/lib/postgresql/17/bin/pg_config --includedir-server
        echo "Checking if server/fmgr.h exists:"
        ls -la $(/usr/lib/postgresql/17/bin/pg_config --includedir-server)/server/fmgr.h || echo "File not found"
        
    - name: Update alternatives
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
      
    - name: mkdir
      run: mkdir build
      
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: build/
      
    - name: make
      run: make
      working-directory: build/