name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc]
        build_type: [Debug, Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Cache APT packages
        uses: actions/cache@v4.2.4
        with:
          path: /var/cache/apt/archives
          key: apt-cache-ubuntu-${{ runner.os }}-${{ hashFiles('**/.github/workflows/*.yml') }}
          restore-keys: |
            apt-cache-ubuntu-${{ runner.os }}-

      - name: Install base dependencies
        run: |
          sudo apt update && sudo apt install -y \
            git \
            gcc \
            cmake \
            make \
            curl \
            ca-certificates \
            pkg-config \
            zlib1g \
            zlib1g-dev \
            libzstd-dev \
            liblz4-dev \
            bzip2 \
            libbz2-dev

      - name: Install PostgreSQL from official repository
        run: |
          # Add official PostgreSQL repository
          sudo install -d /usr/share/postgresql-common/pgdg
          sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
          sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt update
          
          # Install PostgreSQL with ALL development packages
          sudo apt install -y \
            postgresql-17 \
            postgresql-server-dev-17 \
            postgresql-client-17 \
            postgresql-contrib-17 \
            postgresql-common \
            postgresql-server-dev-all \
            libpq-dev \
            libpq5

      - name: Set PostgreSQL environment and verify installation
        run: |
          # Add PostgreSQL binaries to PATH
          echo "/usr/lib/postgresql/17/bin" >> $GITHUB_PATH
          
          # Verify installation
          echo "=== PostgreSQL Installation Verification ==="
          /usr/lib/postgresql/17/bin/pg_config --version
          echo "Include directory: $(/usr/lib/postgresql/17/bin/pg_config --includedir)"
          echo "Server include directory: $(/usr/lib/postgresql/17/bin/pg_config --includedir-server)"
          echo "Library directory: $(/usr/lib/postgresql/17/bin/pg_config --libdir)"
          echo "Package library directory: $(/usr/lib/postgresql/17/bin/pg_config --pkglibdir)"
          
          # Verify critical header files exist
          SERVER_INC=$(/usr/lib/postgresql/17/bin/pg_config --includedir-server)
          if [ -f "$SERVER_INC/fmgr.h" ]; then
            echo "✓ fmgr.h found at: $SERVER_INC/fmgr.h"
          else
            echo "✗ fmgr.h not found at expected location: $SERVER_INC/fmgr.h"
            exit 1
          fi

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            export CC=/usr/bin/gcc
          else
            export CC=/usr/bin/clang
          fi
          
          # Configure with CMAKE
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          
          # Build with verbose output
          make VERBOSE=1

      - name: Install Extension
        run: |
          cd build
          sudo make install
          
          # Verify installation
          PGLIB_DIR=$(/usr/lib/postgresql/17/bin/pg_config --pkglibdir)
          if [ -f "$PGLIB_DIR/pgexporter_ext.so" ]; then
            echo "✓ Extension installed successfully at $PGLIB_DIR/pgexporter_ext.so"
            ls -la "$PGLIB_DIR"/pgexporter_ext*
          else
            echo "✗ Extension installation failed"
            echo "Contents of PostgreSQL lib directory:"
            ls -la "$PGLIB_DIR/" || echo "Directory not found"
          fi

      - name: Start PostgreSQL and test extension
        run: |
          # Start PostgreSQL service
          sudo systemctl start postgresql
          sudo -u postgres createdb testdb
          
          # Test extension installation
          sudo -u postgres psql -d testdb -c "CREATE EXTENSION pgexporter_ext;" || {
            echo "Extension creation failed, checking logs..."
            sudo journalctl -u postgresql --no-pager -n 50
            exit 1
          }
          
          sudo -u postgres psql -d testdb -c "SELECT extname, extversion FROM pg_extension WHERE extname = 'pgexporter_ext';"
          echo "✓ Extension loaded and tested successfully"

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.compiler }}-${{ matrix.build_type }}
          path: |
            build/
            !build/CMakeFiles/
          retention-days: 7